// Defines

#include "system/detect.h"

// Types (include all files to expose them in the disassembler)

// external types (c-ified)
#include "async/object.h"
#include "async/queue.h"
#include "external/d3d9/d3d9.h"

#include "lua/lua.h"

#include "bc/debug/errorstack.h"
#include "bc/file/fileinfo.h"
#include "bc/file/filesystem.h"
#include "bc/file/infomask.h"
#include "bc/file/inode.h"
#include "bc/file/mode.h"
#include "bc/file/processdir.h"
#include "bc/file/removedirectory.h"
#include "bc/file/stream.h"
#include "bc/file/streaminginfo.h"
#include "bc/lock/do_once.h"
#include "bc/lock/mutex.h"
#include "bc/os/file.h"
#include "bc/os/file_data.h"
#include "bc/storage/storageunit.h"
#include "bc/storage/storageunithandle.h"
#include "bc/string/quickformat.h"
#include "bc/stringconversion/codepagetoutf8.h"
#include "bc/stringconversion/passthrough.h"
#include "bc/stringconversion/utf16toutf8.h"
#include "bc/system_file/stacked/filefunc.h"
#include "bc/system_file/stacked/fileparms.h"
#include "bc/system_using/using.h"
#include "bc/thread/thread.h"
#include "bc/thread/tls.h"
#include "bc/time/timeconst.h"
#include "bc/time/types.h"
#include "bc/util/buffer.h"
#include "bc/util/offset.h"

#include "camera/camera.h"

#include "client/commandmanager.h"
#include "client/gameclientcommands.h"

#include "cmd/option.h"

#include "common/array.h"
#include "common/datarecycler.h"
#include "common/datastore.h"
#include "common/handle.h"
#include "common/instance.h"
#include "common/mempool.h"
#include "common/rcstring.h"
#include "common/refcount.h"
#include "common/status.h"

#include "console/command.h"
#include "console/default_settings.h"
#include "console/hardware.h"
#include "console/line.h"
#include "console/types.h"
#include "console/var.h"

#include "crypto/hmac.h"
#include "crypto/sha1.h"

#include "cursor/types.h"

#include "daynight/dnglare.h"

#include "event/context.h"
#include "event/handler.h"
#include "event/id_table.h"
#include "event/keydown.h"
#include "event/message.h"
#include "event/thread.h"
#include "event/timer.h"
#include "event/types.h"

#include "framescript/event_object.h"
#include "framescript/object.h"

#include "gx/batch.h"
#include "gx/blit.h"
#include "gx/buffer.h"
#include "gx/caps.h"
#include "gx/d3d9.h"
#include "gx/device.h"
#include "gx/format.h"
#include "gx/light.h"
#include "gx/matrix_stack.h"
#include "gx/monitor_mode.h"
#include "gx/opengl.h"
#include "gx/query.h"
#include "gx/shader.h"
#include "gx/state_bom.h"
#include "gx/string.h"
#include "gx/stringbatch.h"
#include "gx/texture.h"
#include "gx/types.h"

#include "m2/cache.h"
#include "m2/data.h"
#include "m2/light.h"
#include "m2/lighting.h"
#include "m2/model.h"
#include "m2/ribbon.h"
#include "m2/scene.h"
#include "m2/shadereffect.h"
#include "m2/shared.h"
#include "m2/types.h"

#include "map/adt_chunks.h"
#include "map/chunkgeomfactory.h"
#include "map/chunkliquid.h"
#include "map/detaildoodad.h"
#include "map/liquidparticle.h"
#include "map/maparea.h"
#include "map/mapbaseobj.h"
#include "map/mapchunk.h"
#include "map/mapchunkbuf.h"
#include "map/mapdoodaddef.h"
#include "map/mapentity.h"
#include "map/mapobj.h"
#include "map/mapobjdef.h"
#include "map/maprenderchunk.h"
#include "map/mapstaticentity.h"
#include "map/particulate.h"
#include "map/vbb_list.h"
#include "map/weather.h"
#include "map/wmo_chunks.h"

#include "character/component.h"
#include "net/addr.h"
#include "net/characterinfo.h"
#include "net/clientconnection.h"
#include "net/logindata.h"
#include "net/message.h"
#include "net/message_handler.h"
#include "net/netclient.h"
#include "net/neteventqueue.h"
#include "net/netstate.h"
#include "net/realmresponse.h"
#include "net/wowconnection.h"
#include "net/wowconnectionnet.h"
#include "net/wowconnectionresponse.h"
#include "net/wowcsops.h"

#include "nvapi/nvapi.h"

#include "object/CMovementData.h"
#include "object/guid.h"
#include "object/object.h"
#include "object/objectmanager.h"
#include "object/player.h"

#include "os/processorfeatures.h"
#include "os/timemanager.h"

#include "screen/layer.h"

#include "storm/array.h"
#include "storm/atomic.h"
#include "storm/big.h"
#include "storm/cmd.h"
#include "storm/crypto/arc4.h"
#include "storm/hash.h"
#include "storm/list.h"
#include "storm/log.h"
#include "storm/options.h"
#include "storm/queue.h"
#include "storm/region.h"
#include "storm/thread.h"

#include "tempest/box.h"
#include "tempest/matrix.h"
#include "tempest/plane.h"
#include "tempest/quaternion.h"
#include "tempest/range.h"
#include "tempest/rect.h"
#include "tempest/sphere.h"
#include "tempest/vector.h"

#include "text/font.h"

#include "texture/blp.h"
#include "texture/texture.h"
#include "texture/tga.h"

#include "ui/backdropgenerator.h"
#include "ui/framestrata.h"
#include "ui/layoutframe.h"
#include "ui/renderbatch.h"
#include "ui/scriptobject.h"
#include "ui/scriptregion.h"
#include "ui/simplebatchedmesh.h"
#include "ui/simpleframe.h"
#include "ui/simplemodel.h"
#include "ui/simpleregion.h"
#include "ui/simpletexture.h"
#include "ui/simpletop.h"
#include "ui/uiaddon.h"

#include "xml/xml.h"

// include files that define the use of template classes for standard library types
// template classes for whoa types should be entered immediately after where the type is

#include "storm/array/c2ivector.h"
#include "storm/array/float.h"
#include "storm/array/pointer_to_void.h"
#include "storm/array/uint32_t.h"
#include "storm/array/uint8_t.h"

#include "storm/queue/timer_priority_uint32_t.h"

// template types that are defined in our headers, should be declared immediately after the base
// type and not used anywhere else
