#ifndef CONSOLE_TYPES_H
#define CONSOLE_TYPES_H

DECLARE_ENUM(COLOR_T);
DECLARE_ENUM(CATEGORY);
DECLARE_ENUM(EXECMODE);
DECLARE_ENUM(CONSOLERESIZESTATE);

enum COLOR_T {
  DEFAULT_COLOR = 0,
  INPUT_COLOR = 1,
  ECHO_COLOR = 2,
  ERROR_COLOR = 3,
  WARNING_COLOR = 4,
  GLOBAL_COLOR = 5,
  ADMIN_COLOR = 6,
  HIGHLIGHT_COLOR = 7,
  BACKGROUND_COLOR = 8,
  NUM_COLORTYPES
};

enum CATEGORY {
  DEBUG = 0,
  GRAPHICS = 1,
  CONSOLE = 2,
  COMBAT = 3,
  GAME = 4,
  DEFAULT = 5,
  NET = 6,
  SOUND = 7,
  GM = 8,
  NONE = 9,
  LAST
};

enum EXECMODE {
  EM_PROMPTOVERWRITE = 0,
  EM_RECORDING = 1,
  EM_APPEND = 2,
  EM_WRITEFILE = 3,
  EM_NOTACTIVE = 4,
  EM_NUM_EXECMODES
};

enum CONSOLERESIZESTATE {
  CS_NONE = 0,
  CS_STRETCH = 1,
  NUM_CONSOLERESIZESTATES
};

#endif