#ifndef NET_NET_STATE_H
#define NET_NET_STATE_H

DECLARE_ENUM(NETSTATE);

enum NETSTATE {
    NS_UNINITIALIZED = 0,
    NS_INITIALIZING  = 1,
    NS_INITIALIZED   = 2,
    NS_DISCONNECTING = 3,
    NS_CONNECTING    = 4,
    NS_CONNECTED     = 5,
};

#endif
