-- #include "cmapbaseobj.lua"

local CMapChunk = Struct('CMapChunk', CMapBaseObj)
    :C2iVector('aIndex')
    :C2iVector('sOffset')
    :C2iVector('cOffset')
    :CAaSphere('sphere')
    :CAaBox('bbox')
    :C3Vector('bottomRight')
    :C3Vector('topLeft')
    :C3Vector('topLeftCoords')
    :float('distToCamera')
    :CAaBox('bbox2')
    :ptr('detailDoodadInst')
    :ptr('renderChunk')
    :field('unk_AC', 'int32')
    :field('areaId', 'int32')
    :field('unk_B4', 'int32')
    :field('unk_B8', 'int32')
    :field('unk_BC', 'int32')
    :field('unk_C0', 'int32')
    :TSList('doodadDefLinkList')
    :TSList('mapObjDefLinkList')
    :TSList('unkList')
    :TSList('lightLinkList')
    :TSList('mapSoundEmitterLinkList')
    :TSList('liquidChunkLinkList')
    :ptr('chunkInfoBeginPtr')
    :ptr('header')
    :ptr('lowQualityTexMap')
    :ptr('predTexture')
    :ptr('vertices')
    :ptr('vertexShading')
    :ptr('normals')
    :ptr('shadowMap')
    :ptr('layers')
    :ptr('additionalShadowmap')
    :ptr('MCRF')
    :ptr('liquid')
    :ptr('soundEmitters')
    :field('unk_140', 'int32')
    :field('unk_144', 'int32')
    :field('unk_148', 'int32')
    :ptr('unk_14C')
    :field('unk_150', 'int32')
    :field('unk_154', 'int32')

local address = 0x00795e25 -- at CWorldScene__LocateViewer3
debugger_onBreakpoint = nil
function onBreakpoint()
    loadStructToTable(CMapChunk, ECX)
    debugger_onBreakpoint = nil
    debug_removeBreakpoint(address)
    debug_continueFromBreakpoint(co_run)
    return 1
end

debug_setBreakpoint(address)
debugger_onBreakpoint = onBreakpoint
