-- #include "cmapbaseobj.lua"

local CMapStaticEntity = Struct("CMapStaticEntity", CMapBaseObj)
    :paddingTo(0x28)
    :flag32("unkFlags")
    :int32("unkCounter")
    :float("unk_030")
    :ptr("CM2Model", "model")
    :CAaSphere("sphere")
    :CAaBox("bbox")
    :C3Vector("vec2")
    :C3Vector("position")
    :float("scale")
    :paddingTo(0x80)
    :float("unkFloat")
    :CImVector("m2AmbietColor")
    :CImVector("m2DiffuseColor")
    :float("unk_08C")