#!/usr/bin/env bash

if [ $# -eq 0 ]
  then
    echo "Select a version to use"
    exit 1
fi

./script/build-ce-loader-script -i $1/cgunit.lua -o $2/Load_CGUnit.lua
./script/build-ce-loader-script -i $1/cgplayer.lua -o $2/Load_CGPlayer.lua
./script/build-ce-loader-script -i $1/cgitem.lua -o $2/Load_CGItem.lua
./script/build-ce-loader-script -i $1/cgcontainer.lua -o $2/Load_CGContainer.lua
./script/build-ce-loader-script -i $1/cgcorpse.lua -o $2/Load_CGCorpse.lua
./script/build-ce-loader-script -i $1/cmapentity.lua -o $2/Load_CMapEntity.lua
./script/build-ce-loader-script -i $1/cmaparea.lua -o $2/Load_CMapArea.lua
./script/build-ce-loader-script -i $1/cmapchunk.lua -o $2/Load_CMapChunk.lua
./script/build-ce-loader-script -i $1/cmapobjdef.lua -o $2/Load_CMapObjDef.lua
./script/build-ce-loader-script -i $1/cmapobjdefgroup.lua -o $2/Load_CMapObjDefGroup.lua
