#ifndef CMD_OPTION_H
#define CMD_OPTION_H

DECLARE_ENUM(CMDOPT);

enum CMDOPT {
  CMD_D3D = 0,
  CMD_D3D9EX = 1,
  CMD_DATA_DIR = 2,
  CMD_NO_LAG_FIX = 3,
  CMD_LOADFILE = 4,
  CMD_GAMETYPE = 5,
  CMD_OPENGL = 6,
  CMD_SW_TNL = 7,
  CMD_TIMEDEMO = 8,
  CMD_DEMOREZ = 9,
  CMD_DEMODEPTH = 10,
  CMD_DEMODETAIL = 11,
  CMD_DEMOSOUND = 12,
  CMD_FULL_SCREEN = 13,
  CMD_22050HZ = 14,
  CMD_NO_WARNINGS = 15,
  CMDOPTS = 16
};

#endif